package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/ACTIVE.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/re/workspace/8-2-build-windows-amd64-cygwin/jdk8u112/7884/corba/src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Thursday, September 22, 2016 9:33:09 PM PDT
*/

public interface ACTIVE
{

  /** Object adapter state that indicates normal request processing.
   */
  public static final short value = (short)(1);
}
